if game:GetService('Players').LocalPlayer.UserId == 3656041166 then
    game:GetService('Players').LocalPlayer:Kick("Rayx gay")
end
if game:GetService('Players').LocalPlayer.UserId == 3206348312 then
    game:GetService('Players').LocalPlayer:Kick("You're a clown 🤡")
end
if game:GetService('Players').LocalPlayer.UserId == 2211015718 then
    game:GetService('Players').LocalPlayer:Kick("keep using that fake headless broke ass")
end
if game:GetService('Players').LocalPlayer.UserId == 1128575429 then
    game:GetService('Players').LocalPlayer:Kick("racist 8 year old")
end